### ISSUE TITLE
Visualization issues

### ISSUE THREAD

**Issue by xingjiy** [hulianyuyy/CorrNet_Plus#4]
I'm visualizing the trained CSL-Daily model and noticed that the image generated by the Grad-CAM visualization of the spatial weight map doesn't have the yellowish trajectory highlights displayed
![20240530222134](https://github.com/hulianyuyy/CorrNet_Plus/assets/51338752/21a66fc5-2d5c-4981-8653-f55a2b4023b7)

**Comment by hulianyuyy** [comment]
Have you loaded the pretrained weight? Or you may test the .py file on the phoenix2014 dataset to verify whether it works correctly.

**Comment by xingjiy** [comment]
I tried to import the pt weight file of CSL-Daily that I trained myself and the pt weight file that you gave, and this effect appeared. Later, I will try to see if Pheonix2014 can run successfully

**Comment by xingjiy** [comment]
> Have you loaded the pretrained weight? Or you may test the .py file on the phoenix2014 dataset to verify whether it works correctly.

I have tried the Grad-CAM visualization of spatial weight maps and Grad-CAM visualization of correlation maps on the Pheonix2014 dataset using the weight files you provided, and they work fine and show bright yellow trajectories. However, although CSL-Daily runs normally, there is still no bright yellow trajectory on the top of the generated weight images.

**Comment by hulianyuyy** [comment]
I check it and found that the ```weights``` for the corr2 module of the CorrNet, are too small ([-5.0640e-41, -3.7396e-41,  1.1495e-41]), and bring the outputs to zero, thus cause the weight maps to be all zeros. This reflects the corr2 module ignores the spatial weighting part on the csl-daily dataset. The corr3 doesn't exhibit this behavior, and you may use it for visualization.

**Comment by xingjiy** [comment]
> I check it and found that the `weights` for the corr2 module of the CorrNet, are too small ([-5.0640e-41, -3.7396e-41, 1.1495e-41]), and bring the outputs to zero, thus cause the weight maps to be all zeros. This reflects the corr2 module ignores the spatial weighting part on the csl-daily dataset. The corr3 doesn't exhibit this behavior, and you may use it for visualization.

May I ask if the main thing is to change this code: “model.conv2d.corr2.conv_back.register_forward_hook(forward_hook)”

**Comment by xingjiy** [comment]
Generating weight maps has been solved so far, but it is currently found that visualization for correlation maps still has problems displaying on the CSL-Daily dataset.
![Snipaste_2024-06-06_17-26-34](https://github.com/hulianyuyy/CorrNet_Plus/assets/51338752/38bdab2f-9d72-4a90-b078-9ef8935970ec)

**Comment by hulianyuyy** [comment]
You can set line 295 in ./corr_map_generation/resnet.py as ```out_cam = -affinities[t,i]```. We add a negative symbol in this line. As the alpha[0] parameter in the pretrained weights is negative, we add a negative symbol to correct its influence and show the correct visualizations.
