### ISSUE TITLE
The downloaded model weights do not match the shape of the model

### ISSUE THREAD

**Issue by smellno** [hulianyuyy/CorrNet_Plus#5]
RuntimeError: Error(s) in loading state_dict for SLRModel:
        size mismatch for conv1d.fc.weight: copying a param with shape torch.Size([1024, 1116]) from checkpoint, the shape in current model is torch.Size([1024, 1086]).
        size mismatch for classifier.weight: copying a param with shape torch.Size([1024, 1116]) from checkpoint, the shape in current model is torch.Size([1024, 1086]).

**Comment by hulianyuyy** [comment]
It seems that you want to load a pretrained model for PHOENIX14-T which has a vocabulary of 1116. Have you changed the dataset into 'phoenix2014-T' in the baseline.yaml file?

**Comment by smellno** [comment]
Hi, I have changed the dataset to 'phoenix2014-T' in the baseline.yaml file. But it still shows that the training model parameters do not match the model. Loaded the training model parameters and it shows conv1d.fc.weight: torch.Size([1024, 1116]), classifier.weight: torch.Size([1024, 1116])? Doesn't match the 1086 classification of the dataset

**Comment by smellno** [comment]
![图片2](https://github.com/user-attachments/assets/fb08bda2-65f5-4f03-adfc-9064549f3dea)

**Comment by hulianyuyy** [comment]
It seems strange because the phoenix2014-T dataset has a vocabulary of 1116 signs. The shape of the loaded weights is correct. It seems that the config file may be wrong currently. You could paste it here for a check.

**Comment by smellno** [comment]
I don't know why the number of phrases in the previously downloaded ‘’tf-logs/CorrNet/preprocess/phoenix2014-T/gloss_dict.npy‘’ is 1086, but the new ‘’tf-logs/CorrNet_Plus/preprocess/phoenix2014-T/gloss_dict.npy‘’ I used with CorrNet_Plus works fine! Thank you very much!
